/*
 * SkyGuard AI — ESP32 Lightweight Edge Model (SIH PS-26073)
 * Automatically generated by model_converter.py
 * RAM footprint: < 1.5 KB | Flash footprint: < 3.2 KB | Latency: ~12 microseconds
 */

#ifndef SKYGUARD_EDGE_MODEL_H
#define SKYGUARD_EDGE_MODEL_H

#include <stdbool.h>
#include <math.h>

typedef struct {
    float temp;
    float press;
    float hum;
    float temp_delta;
    float press_delta;
    float hum_delta;
    float temp_std_5;
} EdgeFeatureVector;

static inline bool skyguard_edge_screen_anomaly(const EdgeFeatureVector *v) {
        if (v->temp <= 19.7729f) {
            if (v->press_delta <= -37.1863f) {
                return true;
            } else {
                if (v->press <= 1030.9594f) {
                    if (v->temp_std_5 <= 0.0125f) {
                        return true;
                    } else {
                        return false;
                    }
                } else {
                    return true;
                }
            }
        } else {
            return true;
        }
}

#endif // SKYGUARD_EDGE_MODEL_H
